# Generated by Django 3.1.2 on 2020-10-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201013_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user_who_liked',
            field=models.CharField(default='', max_length=8),
        ),
    ]
