# Generated by Django 3.1.2 on 2020-11-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20201123_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='image_urll',
            new_name='image_url',
        ),
    ]
