# Generated by Django 3.1.2 on 2020-10-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
